[package]
name = "aztunnel"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "forward"
path = "src/bin/client.rs"

[[bin]]
name = "forwardserver"
path = "src/bin/client.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
